In [2]:
#importando a biblioteca 
import numpy as np

In [4]:
#criando listas e arrays
lista = [1,2,3,4,5,6,7]

array = np.array(lista)

In [14]:
#exibe tipos de dados
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
#criando array com zeros via lib
array_zeros = np.zeros(10)
print(array_zeros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
#atribuindo valores a lista - alterando
array[0] = 10
print(array[0])

10


In [17]:
#criando matrizes 
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
#operaçoes matematicas 
lista_notas = [10,5,8,9,7,4,2,3]
array_notas = np.array(lista_notas)

In [21]:
#resultado de nota maxima e minima
print('Maxima',array_notas.max())
print('Minima',array_notas.min())
print('Desvio Padrao',array_notas.std())
print('Media',array_notas.mean())
print('Posicao Minima',array_notas.argmin())
print('Posicao Maxima',array_notas.argmax())

Maxima 10
Minima 2
Desvio Padrao 2.7386127875258306
Media 6.0
Posicao Minima 6
Posicao Maxima 0


In [ ]:
# Informar 10 notas e atribuir em uma lista array

# Funcao Gerar numero
def num_aleat(num_min,num_max):
    import random
    num_ger = random.randrange(num_min,num_max)
    return num_ger

def exibcontagem(conttela):
    cont = 0
    while cont <= conttela:
        print('Processando',cont)
        cont += 1
    
num_min = 0 #nota minima
num_max = 10 #nota maxima
num_ger = 10 # qtde de notas

for in num

In [22]:
# Funcao Gerar numero
def num_aleat(num_min,num_max):
    import random
    num_ger = random.randrange(num_min,num_max)
    return num_ger

def exibcontagem(conttela):
    cont = 0
    while cont <= conttela:
        print('Processando',cont)
        cont += 1
    


#programa principal
    
num_min = 1
num_max = 100
num_ger = num_aleat(num_min,num_max)

print('Jogo Adivinha Numero')
print('Gerando Numero Aleatório de ',num_min,num_max )
conttela = 10
exibcontagem(conttela)

numinfor = 0
erro = 0
print(num_ger)

while numinfor != num_ger and numinfor != 'sair':
    print('Numero sorteado de',num_min,num_max)
    numinfor = input('Informe um numero de, sair para terminar  ')
    numinfor = int(numinfor)

    if numinfor != num_ger:
        print('Voce errou, tente novamente')
        erro += 1
        if numinfor < num_ger:
            print('Valor Baixo')
        elif numinfor > num_ger:
            print('Valor Alto')

    elif numinfor == num_ger:
        print('Parabens, voce acertou!')
        print('Total Erros',erro)

Jogo Adivinha Numero
Gerando Numero Aleatório de  1 100
Processando 0
Processando 1
Processando 2
Processando 3
Processando 4
Processando 5
Processando 6
Processando 7
Processando 8
Processando 9
Processando 10
40
Numero sorteado de 1 100
Voce errou, tente novamente
Valor Baixo
Numero sorteado de 1 100
Voce errou, tente novamente
Valor Baixo
Numero sorteado de 1 100


ValueError: invalid literal for int() with base 10: ''