In [10]:
##01 - Numpy
#importando a biblioteca 
import numpy as np

#criando listas e arrays
lista = [1,2,3,4,5,6,7]

array = np.array(lista)

#exibe tipos de dados
print(type(lista))
print(type(array))

#criando array com zeros via lib
array_zeros = np.zeros(10)
print(array_zeros)

#atribuindo valores a lista - alterando
array[0] = 10
print(array[0])

#criando matrizes 
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

#operaçoes matematicas 
lista_notas = [10,5,8,9,7,4,2,3]
array_notas = np.array(lista_notas)

#resultado de nota maxima e minima
print('Maxima',array_notas.max())
print('Minima',array_notas.min())
print('Desvio Padrao',array_notas.std())
print('Media',array_notas.mean())
print('Posicao Minima',array_notas.argmin())
print('Posicao Maxima',array_notas.argmax())

<class 'list'>
<class 'numpy.ndarray'>
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Maxima 10
Minima 2
Desvio Padrao 2.7386127875258306
Media 6.0
Posicao Minima 6
Posicao Maxima 0


In [11]:
# Informar 10 notas e atribuir em uma lista array

# Funcao Gerar numero
def num_aleat(num_min,num_max):
    import random
    num_ger = random.randrange(num_min,num_max)
    return num_ger

def exibcontagem(conttela):
    cont = 1
    cont_time = 10
    while cont <= conttela:
        print('Processando',cont)
        cont += 1
        exib_time(cont_time)

    

def exib_time(cont_time):
    cont = 1
    exibir = ''
    while cont <= cont_time:
        exibir = exibir + '*'
        cont += 1
        print(exibir)

num_min = 0 #nota minima
num_max = 10 #nota maxima
num_ger = 10 # qtde de notas
notas_lista = []
nota_cont = 0
nota_cont_exib = 1

for _ in range(num_ger):
    notas_lista.insert(num_ger,num_aleat(num_min,num_max))
    
    conttela = 3
    exibcontagem(conttela)
    print('Nota',nota_cont_exib,'Processada')
    print('Nota',notas_lista[nota_cont])
    nota_cont += 1
    nota_cont_exib += 1

print(notas_lista)

#importando a biblioteca 
import numpy as np

notas_array = np.array(notas_lista)

#resultado de nota maxima e minima
print('Maxima',notas_array.max())
print('Minima',notas_array.min())
print('Desvio Padrao',notas_array.std())
print('Media',notas_array.mean())
print('Posicao Minima',notas_array.argmin())
print('Posicao Maxima',notas_array.argmax())


Processando 1
*
**
***
****
*****
******
*******
********
*********
**********
Processando 2
*
**
***
****
*****
******
*******
********
*********
**********
Processando 3
*
**
***
****
*****
******
*******
********
*********
**********
Nota 1 Processada
Nota 1
Processando 1
*
**
***
****
*****
******
*******
********
*********
**********
Processando 2
*
**
***
****
*****
******
*******
********
*********
**********
Processando 3
*
**
***
****
*****
******
*******
********
*********
**********
Nota 2 Processada
Nota 1
Processando 1
*
**
***
****
*****
******
*******
********
*********
**********
Processando 2
*
**
***
****
*****
******
*******
********
*********
**********
Processando 3
*
**
***
****
*****
******
*******
********
*********
**********
Nota 3 Processada
Nota 6
Processando 1
*
**
***
****
*****
******
*******
********
*********
**********
Processando 2
*
**
***
****
*****
******
*******
********
*********
**********
Processando 3
*
**
***
****
*****
******
*******
*******

In [34]:
##02 - Mascara Booleana

import numpy as np

#criando uma lista de covis 
lista_covid = np.array(['POS','NEG','NEG','POS','NEG','POS'])
#exibindo lista
print(lista_covid)

#trazendo resultados da lista numpy - true e false
mask = lista_covid == 'POS'
print(mask)
#trazendo resultados filtrados 
print(lista_covid[mask])
#altera dados so array dos dados filtrados
lista_covid[mask] = 'C19'
print(lista_covid)


# Funcao Gerar numero
def num_aleat(num_min,num_max):
    import random
    num_ger = random.randrange(num_min,num_max)
    return num_ger


num_min = 0 #nota minima
num_max = 10 #nota maxima
num_ger = 10 # qtde de notas
notas_lista = []
nota_cont = 0
nota_cont_exib = 1

for _ in range(num_ger):
    notas_lista.insert(num_ger,num_aleat(num_min,num_max))
    
    conttela = 3
    print('Nota',nota_cont_exib,'Processada')
    print('Nota',notas_lista[nota_cont])
    nota_cont += 1
    nota_cont_exib += 1

print(notas_lista)

#importando a biblioteca 
import numpy as np

#exibir dados 
notas_array = np.array(notas_lista)

#filtrar notas > 5 
mask_aprovados = notas_array > 5
#exibir aprovados 
print(notas_array[mask_aprovados])



['POS' 'NEG' 'NEG' 'POS' 'NEG' 'POS']
[ True False False  True False  True]
['POS' 'POS' 'POS']
['C19' 'NEG' 'NEG' 'C19' 'NEG' 'C19']
Nota 1 Processada
Nota 7
Nota 2 Processada
Nota 0
Nota 3 Processada
Nota 7
Nota 4 Processada
Nota 2
Nota 5 Processada
Nota 1
Nota 6 Processada
Nota 6
Nota 7 Processada
Nota 8
Nota 8 Processada
Nota 3
Nota 9 Processada
Nota 3
Nota 10 Processada
Nota 8
[7, 0, 7, 2, 1, 6, 8, 3, 3, 8]
[7 7 6 8 8]


In [51]:
##3 - Series Panda

#importa bibliotecas 
import pandas as pd

# cria uma lista e transforma em pandas series 
lista_panda = [10,12,77,88,77,12,25]
serie_pandas = pd.Series(lista_panda)
print(serie_pandas)
print(serie_pandas[0])

# series com indices por nomes 
lista_notas = {'A' : 10, 'B': 8, 'C' : 5}
print(lista_notas)
series_notas = pd.Series(lista_notas)
print(series_notas)
print(series_notas['A'])
print(series_notas.mean())
print(series_notas.median())
print(series_notas.describe())

0    10
1    12
2    77
3    88
4    77
5    12
6    25
dtype: int64
10
{'A': 10, 'B': 8, 'C': 5}
A    10
B     8
C     5
dtype: int64
10
7.666666666666667
8.0
count     3.000000
mean      7.666667
std       2.516611
min       5.000000
25%       6.500000
50%       8.000000
75%       9.000000
max      10.000000
dtype: float64


In [109]:
import pandas as pd

# Dicionário de dados
dictionary = {
    'Autores': ['Autor A', 'Autor B', 'Autor C', 'Autor D', 'Autor E'],
    'Livros': ['Livro A', 'Livro B', 'Livro C', 'Livro D', 'Livro E'],
    'Precos': [1, 2, 3, 4, 5]
}

# Criação do DataFrame
df = pd.DataFrame(dictionary)

# Exibindo o DataFrame
print(df)

# Calculando a média dos preços
media_precos = df['Precos'].mean()
print("Média dos Preços:", media_precos)

# Criando uma máscara booleana para filtrar autores específicos
mask = df['Autores'] == 'Autor A'
print("Filtrando Autor A:")
print(df[mask])

# Incluindo novos dados no DataFrame
novo = pd.DataFrame([{'Autores': 'Autor 7', 'Livros': '7777777', 'Precos': 777}])
df = pd.concat([df, novo], ignore_index=True)

# Exibindo o DataFrame atualizado
print("DataFrame atualizado:")
print(df)

#Correcao de dados 
masc_correcao  = df['Livros'] == 'Livro B'
df.loc[masc_correcao,'Livros'] = 'Livro B+'

# Exibindo o DataFrame atualizado
print("DataFrame atualizado e corrigido:")
print(df)



   Autores   Livros  Precos
0  Autor A  Livro A       1
1  Autor B  Livro B       2
2  Autor C  Livro C       3
3  Autor D  Livro D       4
4  Autor E  Livro E       5
Média dos Preços: 3.0
Filtrando Autor A:
   Autores   Livros  Precos
0  Autor A  Livro A       1
DataFrame atualizado:
   Autores   Livros  Precos
0  Autor A  Livro A       1
1  Autor B  Livro B       2
2  Autor C  Livro C       3
3  Autor D  Livro D       4
4  Autor E  Livro E       5
5  Autor 7  7777777     777
DataFrame atualizado e corrigido:
   Autores    Livros  Precos
0  Autor A   Livro A       1
1  Autor B  Livro B+       2
2  Autor C   Livro C       3
3  Autor D   Livro D       4
4  Autor E   Livro E       5
5  Autor 7   7777777     777
